CREATING A NUMPY ARRAY AND ITS ATTRIBUTES

In [7]:
#importing numpy library
import numpy as np

#creating a list named "my_list"
my_list = [1,3,5,7,9]

# creating a 1-D numpy array from "my_list"
my_arr = np.array(my_list)

#printing my_arr as output
print(my_arr)

#Creating a 0-D array
arr_0d = np.array(42)
print(arr_0d)

#Creating a 2-D array

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

# Creating a 3-D array

arr_3d = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(arr_3d)

[1 3 5 7 9]
42
[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
# Creating array and its attributes

arr = np.array([[1,2,3,4,], [6,7,8,9]])
print(arr) #printing the array
print(arr.shape) #printing the shape of array
print(arr.ndim) #Dimensions
print(arr.dtype) #Types........
print(arr.size) #Size......

[[1 2 3 4]
 [6 7 8 9]]
(2, 4)
2
int64
8


ACCESSING AND MANIPULATING ARRAY ELEMENTS

In [14]:
# Accessing 1-D array elements
my_arr = np.array([2,5,7,9])
print(my_arr[2])

[2 5 7 9]


In [15]:
# Accessing 2-D array elements

my_arr = np.array([[2,5,7,9], [1,3,5,7]])
print(my_arr[1,2])

[[2 5 7 9]
 [1 3 5 7]]


In [21]:
# Accessing 3D array elements

my_arr = np.array([[[2,5,7,9],[1,3,5,7],[2,5,7,9],[1,3,5,7]]])
print(my_arr[0,1,2])


5


NEGATIVE INDEXING

In [20]:
#Accessing 2-D array elements with negative indexing

my_arr = np.array([[2,5,7,9], [1,3,5,7]])
print(my_arr[1,-2])


5


SLICING ARRAYS

# imporant concept while slicing arrays
# array[start:end]
#array[start:end:step]

In [22]:
#Slicing a 1-D Numpy Array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25])
print(arr[1:5]) #slicing
print(arr[1:5:2]) #slicing with step size
print(arr[::2]) #slicing with step
print(arr[0:-1]) #Negative

[2 3 4 5]
[2 4]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [24]:
#Slicing a 2-D Numpy Array

arr = np.array([[1,3,5,7],[2,4,6,8]])
print(arr[1,1:-1])




[4 6]
7


#HOMEWORK: Experiment with slicing on a 3-D Array

In [25]:
#Slicing a 3-D Numpy Array
arr = np.array ([[[1,2,3,4],[5,6,7,8],[9,8,7,6]]])
print(arr[0,1,2])

7


CLASSWORK

QSN 1 : Create a Numpy Array from a list [7,14,21,28]. print the array

In [26]:
#importing numpy
import numpy as np

#creating a list name my_list
my_list = [7,14,21,28]

#creating a 1-D numpy array from "my_list"
my_arr = np.array(my_list)

#printing my_arr as output
print(my_arr)




[ 7 14 21 28]


QSN 2 Create a 2D numpy Array [[5,10,15], [20,25,30]] print its shape and number of dimension using array.ndim


In [29]:
import numpy as np
array = np.array([[5,10,15],[20,25,30]])
print(arr.ndim)


3


In [ ]:
# QSN 3 use np.zeros to create 2D array of a shape (2,3). Then use np.arrange to create an array from 0 to 12 with a step of 3. print both arrays.

In [31]:
# importing numpy
import numpy as np

# creating 2D array of a shape (2,3)
zeros_array = np.zeros((2,3))

# printing

print("2 D arrays of zeros (shape 2 * 3)")

#printing zeros_array
print(zeros_array)

#arranging an array from 0 to 12 with a step of 3
arrange_zeros = np.arange(0,12,3)

#printing arrange_zeros
print(arrange_zeros)


2 D arrays of zeros (shape 2 * 3)
[[0. 0. 0.]
 [0. 0. 0.]]
[0 3 6 9]


# Qsn 4 Create a NumpY array [2, 4, 6, 8] Multiply all elements by 3 and print the result

In [34]:
#importing numpy
import numpy as np

# Creating a list my_list

arr = np.array ([2, 4, 6, 8])

result = arr * 3

print(result)

[ 6 12 18 24]


# QSN 5 : Create a NumPy array [1, 3, 5, 7, 9, 11]. Print the third element and a slice from index 1 to 2 (inclusive)

In [35]:
import numpy as np

arr = np.array([1, 3, 5, 7, 9, 11])

third_element = arr[2]
slice_1_to_2 = arr[1:3]

print(third_element)
print(slice_1_to_2)

5
[3 5]
